#!/usr/bin/env bash
# Mine a vanity CREATE2 salt for WCHAN using ERADICATE2.
#
# Usage:
#   ./script/02_mine_vanity_WCHAN.sh base-sepolia
#   ./script/02_mine_vanity_WCHAN.sh eth-sepolia
#   ./script/02_mine_vanity_WCHAN.sh base

set -euo pipefail

# Load .env so RPC URLs are available
if [[ -f .env ]]; then
  set -a
  source .env
  set +a
fi

NETWORK="${1:?Usage: $0 <base|base-sepolia|eth-sepolia>}"
ADDRESSES_FILE="addresses.json"
ERADICATE2="./lib/ERADICATE2/ERADICATE2.x64"
DEPLOYER="0x4e59b44847b379578588920cA78FbF26c0B4956C"
PATTERN="ba5ed0000"

# Resolve chain ID and RPC URL env var from network name
case "$NETWORK" in
  base)         CHAIN_ID="8453";     RPC_VAR="BASE_RPC_URL" ;;
  base-sepolia) CHAIN_ID="84532";    RPC_VAR="BASE_SEPOLIA_RPC_URL" ;;
  eth-sepolia)  CHAIN_ID="11155111"; RPC_VAR="ETH_SEPOLIA_RPC_URL" ;;
  *)            echo "Error: Unknown network '$NETWORK'. Use 'base', 'base-sepolia', or 'eth-sepolia'." >&2; exit 1 ;;
esac

if [[ ! -f "$ADDRESSES_FILE" ]]; then
  echo "Error: $ADDRESSES_FILE not found. Run from apps/contracts/." >&2
  exit 1
fi

if [[ ! -x "$ERADICATE2" ]]; then
  echo "Error: ERADICATE2 binary not found. Run 'make' in lib/ERADICATE2/ first." >&2
  exit 1
fi

RPC_URL="${!RPC_VAR:-}"
if [[ -z "$RPC_URL" ]]; then
  echo "Error: $RPC_VAR not set. Run: source .env" >&2
  exit 1
fi

INIT_CODE_FILE="wchan_init_code_${CHAIN_ID}.hex"

# Compute latest init code and save to file + hash to addresses.json
echo "Computing WCHAN init code for $NETWORK (chain $CHAIN_ID)..."
forge script script/process/GetInitCodeHash.s.sol:GetInitCodeHash -vvvv --rpc-url "$RPC_URL"
echo ""

if [[ ! -f "$INIT_CODE_FILE" ]]; then
  echo "Error: $INIT_CODE_FILE not generated by GetInitCodeHash." >&2
  exit 1
fi

INIT_CODE_HASH=$(jq -r --arg chain "$CHAIN_ID" '.[$chain].WCHAN_INIT_CODE_HASH // empty' "$ADDRESSES_FILE")

echo "Network:         $NETWORK (chain $CHAIN_ID)"
echo "Init code hash:  $INIT_CODE_HASH"
echo "Deployer:        $DEPLOYER"
echo "Pattern:         $PATTERN"
echo ""

# Copy init code file next to ERADICATE2 (needs .cl kernels in working dir)
ERADICATE2_DIR="$(dirname "$ERADICATE2")"
cp "$INIT_CODE_FILE" "$ERADICATE2_DIR/"
cd "$ERADICATE2_DIR"
exec ./ERADICATE2.x64 -A "$DEPLOYER" -i "$INIT_CODE_FILE" --matching "$PATTERN"
